name: Convert imaages to swatches
on:
  push:
    branches:
    - main
    paths:
    - images/*

jobs:
  convert-to-swatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Converting images
        run: |
          mkdir -p swatches
          FILES=$(find images/ -type f -name '*.png' -print)
          for FILE in ${FILES}; do
            dest=swatches/swatch-$(basename -- "${FILE%.*}" | tr '[:upper:]' '[:lower:]' | tr '[ .,!;*()]' '-').png
            convert "$FILE" -resize 780x780 -gravity center -extent 800x800 -background white "$dest";
          done
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update swatches
